In [ ]:
!pip install numpy

In [ ]:
import numpy as np  #importing the numpy library

In [ ]:
mylist = [1,2,3]
n = np.array(mylist)
n
type(n)

numpy.ndarray

In [ ]:
list_of_lists = np.array([[1,2,3], [4,5,6], [7,8,9]])
list_of_lists
list_of_lists.shape

(3, 3)

In [ ]:
arr = np.arange(0,10)
arr
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#numpy reshape function
mn = np.arange(0,50)
len(mn)
mn.reshape(5,10)

#resize changes the original dataset but reshape just makes no change in the original copy.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#numpy Linspace
ok = np.linspace(0,7,10)    #return 10 evenly spaced values from 0 to 7,
ok

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
#Generating random values
np.random.rand(3,2)  #generates random numbers between 0 to 1 with the shape of n,m i.e. 3,2 here

array([[0.94343844, 0.21412178],
       [0.17135975, 0.99714827],
       [0.40938672, 0.09683853]])

In [ ]:
a = np.random.randn(3,3)
a   #Return a sample from the "standard normal" distribution.

array([[-1.60672136,  0.72917779,  0.60179054],
       [-0.10671022,  1.57722678,  0.5041691 ],
       [ 0.00787102,  0.46335675, -0.35373646]])

In [ ]:
#Generating random values with random.randint
kk = np.random.randint(4,15,10)  #Generating 10 random nums from low(4) inclusive to high(15) inclusive.
kk
kk.reshape(2,5)

array([[14, 10,  6, 10,  8],
       [10, 13, 10, 13, 12]])

In [ ]:
#Indexing and Slicing
mk = np.random.randint(4,15,10)
mk[-1]
mk[3:7]  #from index 3 to indxx 6
mk[3:]  #from index 3 to the last
mk.resize(2,5)
mk

mk[1,4] #gives element in row 1 and column 4
mk[1, 2:4]  #gives column 2 to 3 of row 1
mk[1:, 1:] #everything starting from row1 and col1.

mk[mk>5]   #any element greater than 5
mk>6

array([[ True,  True,  True,  True, False],
       [ True,  True, False, False, False]])

In [ ]:
#Broadcasting
mk[mk>6] = 5  #changing every number greater than 6 to be 5
mk

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 6, 4]])

In [ ]:
#Creating a copy
mk1 = mk.copy()
#or
mk2 = mk[1:, 1:]

In [ ]:
#DataFrame Introduction.
import pandas as pd
data = pd.read_csv('olympics.csv')
data.head()

df = data.copy()
#df['Country']  #i did not got the correct olympic dataset.
df.head()
df[['award', 'award1']] = df[['Unnamed: 4', 'Unnamed: 5']]
df.head()

KeyError: 'Total'

In [ ]:
df.drop(['Unnamed: 5', 'Unnamed: 4'], axis = 1) #axis=1 means we want to drop the column instead of row